### ISSUE TITLE
Does the 'link' means 'hyper-edge' or 'node-pair-edge' in the link prediction task?

### ISSUE THREAD

**Issue by bbjy** [tadpole/DHNE#4]
Hi, thank you for your work! 
I have a question as stated in the title. For example. there is a hyper-edge "A2, U2, L1" in the test dataset, in the training process, you remove the hyper-edge, and then when predicting, you predict whether the hyper-edge exists, or to predict whether there is an edge between 'A2' and 'U2' (or 'A2' and 'L1' ...)?  
Furthermore, is this method only suitable for the  situation that there are links between any two vertices in the hyper-edge? Considering this situation that  ‘there are edges between A1 and U1, U1 and L1, but there is no edge between A1 and L1’, is this method still suitable? 

Looking forward to your reply! Thank you so much!

**Comment by tadpole** [comment]
Thanks for your interests.
- For your first question, the link means hyper-edge. I predict whether the hyper-edge(A2-U2-L1) exists.
- For your second question, in my paper, i focus on the indecomposable hyperedge.  In this case, the hyperedge has a strong relationship, and cannot expand into multiple pairwise relationships. There are no  links between any two vertices. You can read [my paper](https://tadpole.github.io/files/2018_AAAI_DHNE.pdf) for more details. As for the situation that ‘there are edges between A1 and U1, U1 and L1, but there is no edge between A1 and L1’, it is a tradtional network problem, you can use traditional network embedding method, like most methods in [the survey](http://pengcui.thumedialab.com/papers/NetworkEmbeddingSurvey.pdf), to solve it.

**Comment by bbjy** [comment]
Thank you so much for your reply. I got it. @tadpole
