### ISSUE TITLE
关于输入数据

### ISSUE THREAD

**Issue by Theheavens** [tadpole/DHNE#5]
您好，输入的三元组是怎么抽的，是把网络中所有的三元组都抽出来，还是像random_walk一样抽样，可以重复，且数量由超参决定

**Comment by tadpole** [comment]
一个epoch是所有的三元组，然后随机采样同等数量的负边，具体实现参见dataset.py中的next_batch函数。

https://github.com/tadpole/DHNE/blob/2057b24726468794aa2da01df08bf757dbbb6614/src/dataset.py#L27
